# The URL the site will be built for
base_url = "https://ingredients.lol"

title = "e & r recipes"

description = '''
Collection of recipes.
'''

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false


[markdown]

highlight_code = true
highlight_theme = "cheerfully-light"


[extra]

navigation = [
  { name = "Home", path = "/" },
  { name = "Soups", path = "/soups/" },
  { name = "Mains", path = "/mains/" },
  { name = "Sides", path = "/sides/" },
  { name = "Pasta", path = "/pasta/" },
  { name = "Desserts", path = "/desserts/" },
]

twitter_image = "https://raw.githubusercontent.com/bast/err/main/content/img/wine.png"
